# Generated by Django 6.0.3 on 2026-03-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoimagem',
            options={'verbose_name': 'produto_imagem', 'verbose_name_plural': 'produto_imagens'},
        ),
        migrations.AlterModelOptions(
            name='produtoinfo',
            options={'verbose_name': 'produto_cod', 'verbose_name_plural': 'produtos_cod'},
        ),
        migrations.AlterModelTable(
            name='produtoimagem',
            table='produto_imagens',
        ),
        migrations.AlterModelTable(
            name='produtoinfo',
            table='produtos_cod',
        ),
    ]
